version: "3.8"
services:
  quasar-www:
    image: ghcr.io/emerson-mendonca/quasar-teste-dev:0.0.1
    ports:
      - "80:80"
    restart: unless-stopped
    pull_policy: always
    environment:
      - GH_TOKEN=${GH_TOKEN}
